Implemented todays time under user stats
cthit/hubbit pull request #10
Opened 2021-10-21 18:47 UTC by ViddeM

Solves #5

2021-10-22 10:51 UTC, ViddeM commented
Don't merge yet, should change backend to just use the add / sub without checked stuff.

2021-10-25 19:10 UTC, rosengrenen requested changes

2021-10-25 19:10 UTC, rosengrenen commented on backend/src/schema/user.rs
> +      .map_err(|_| HubbitSchemaError::InternalError)?;
Should probably log an error in the console

2021-10-25 19:10 UTC, rosengrenen commented on frontend/src/dateUtil.ts
> +export function getHoursDiff(a: Date, b: Date): string {
Do we care for singular and plural?

2021-10-25 19:13 UTC, ViddeM commented on backend/src/schema/user.rs
> +      .map_err(|_| HubbitSchemaError::InternalError)?;
Feck

2021-10-25 19:17 UTC, ViddeM commented on frontend/src/dateUtil.ts
> +export function getHoursDiff(a: Date, b: Date): string {
True

2021-10-25 19:24 UTC, ViddeM commented on frontend/src/dateUtil.ts
> +export function getHoursDiff(a: Date, b: Date): string {
Fixed

2021-10-25 19:37 UTC, merged